In [3]:
pip install -U imbalanced-learn


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df= pd.read_csv("creditcard.csv")

In [6]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [8]:
df['Class'].value_counts()

0    284315
1       492
Name: Class, dtype: int64

In [9]:
X= df.drop('Class', axis=1)

In [10]:
y= df.Class

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold


In [12]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [13]:
log_class= LogisticRegression()
grid= {'C':10.0 **np.arange(-2,3), 'penalty': ['l1','l2']}
cv =KFold(n_splits=5, shuffle= False, random_state= None)


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, train_size= 0.7) 

In [15]:
clf= GridSearchCV(log_class, grid, cv= cv, n_jobs= -1, scoring='f1_macro')
clf.fit(X_train, y_train)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan 0.82679684        nan 0.83931654        nan 0.84824261
        nan 0.84893354        nan 0.83777955]
  warnings.warn(
C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_macro')

In [16]:
y_pred= clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85250    38]
 [   55   100]]
0.9989115550718023
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85288
           1       0.72      0.65      0.68       155

    accuracy                           1.00     85443
   macro avg       0.86      0.82      0.84     85443
weighted avg       1.00      1.00      1.00     85443



In [17]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [47]:
y_pred= classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85298     8]
 [   31   106]]
0.9995435553526912
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.93      0.77      0.84       137

    accuracy                           1.00     85443
   macro avg       0.96      0.89      0.92     85443
weighted avg       1.00      1.00      1.00     85443



In [49]:
y_train.value_counts()

0    199009
1       355
Name: Class, dtype: int64

In [51]:
class_weight= dict({0:1, 1:100})

In [52]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier(class_weight=class_weight)
classifier.fit(X_train, y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [53]:
y_pred= classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85303     3]
 [   30   107]]
0.9996137776061234
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.97      0.78      0.87       137

    accuracy                           1.00     85443
   macro avg       0.99      0.89      0.93     85443
weighted avg       1.00      1.00      1.00     85443



# under sampling

In [56]:
from collections import Counter
Counter(y_train)

Counter({0: 199009, 1: 355})

In [58]:
from collections import Counter
from imblearn.under_sampling import NearMiss
ns= NearMiss(0.8)
X_train_ns, y_train_ns= ns.fit_resample(X_train, y_train)
print("The number of classe before fi{}". format (Counter(y_train)))
print("The number of classe before fi{}". format (Counter(y_train_ns)))

C:\Users\Acer\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.8 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classe before fiCounter({0: 199009, 1: 355})
The number of classe before fiCounter({0: 443, 1: 355})


In [61]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()
classifier.fit(X_train_ns, y_train_ns)

RandomForestClassifier()

In [62]:
y_pred= classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[76100  9206]
 [    8   129]]
0.8921620261460856
              precision    recall  f1-score   support

           0       1.00      0.89      0.94     85306
           1       0.01      0.94      0.03       137

    accuracy                           0.89     85443
   macro avg       0.51      0.92      0.49     85443
weighted avg       1.00      0.89      0.94     85443



# over Sampling

In [63]:
from imblearn.over_sampling import RandomOverSampler

In [65]:
os= RandomOverSampler(0.5)
X_train_os, y_train_os= os.fit_resample(X_train, y_train)
print("The number of classe before fi{}". format (Counter(y_train)))
print("The number of classe before fi{}". format (Counter(y_train_os)))

C:\Users\Acer\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(


The number of classe before fiCounter({0: 199009, 1: 355})
The number of classe before fiCounter({0: 199009, 1: 99504})


In [66]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()
classifier.fit(X_train_os, y_train_os)

RandomForestClassifier()

In [67]:
y_pred= classifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[85302     4]
 [   28   109]]
0.9996254813150287
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85306
           1       0.96      0.80      0.87       137

    accuracy                           1.00     85443
   macro avg       0.98      0.90      0.94     85443
weighted avg       1.00      1.00      1.00     85443



# SMOTETomek

In [18]:
from imblearn.combine import SMOTETomek

In [ ]:
SM= SMOTETomek(0.5)
X_train_sm, y_train_sm= SM.fit_resample(X_train, y_train)
print("The number of classe before fi{}". format (Counter(y_train)))
print("The number of classe before fi{}". format (Counter(y_train_sm)))

C:\Users\Acer\Anaconda3\lib\site-packages\imblearn\utils\_validation.py:587: FutureWarning: Pass sampling_strategy=0.5 as keyword args. From version 0.9 passing these as positional arguments will result in an error
  warnings.warn(
